site_name: PSYC 3010 - Programming for Behavioral Scientists
site_url: https://trentwirth.github.io/3010/
repo_url: https://github.com/trentwirth/trentwirth.github.io
site_dir: 'site'
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.indexes
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


nav: 
  - Home: 
    - index.md
    - About: about.md
  - Core Path: 
    - Core Path: core_path/index.md
    - Step 1 - Your Computer: core_path/Step_01.md
    - Step 2 - Intro to Python: core_path/Step_02.md
    - Step 3 - Using Python: core_path/Step_03.md
    - Step 4 - Operators & Expressions: core_path/Step_04.md
    - Step 5 - Conditionals: core_path/Step_05.md
    - Step 6 - Control Structures: core_path/Step_06.md
    - Step 7 - Functions I: core_path/Step_07.md
    - Step 8 - Functions II: core_path/Step_08.md
    - Step 9 - Debugging: core_path/Step_09.md
    - Step 10 - OOP I: core_path/Step_10.md
    - Step 11 - OOP II: core_path/Step_11.md
    - Step 12 - Modularity & File I/O I: core_path/Step_12.md
    - Step 13 - Modularity & File I/O II: core_path/Step_13.md
  - Data Path:
    - Data Path: data_path/index.md
    - Step 14 - Data Structures I: data_path/Step_14.md
    - Step 15 - Data Structures II: data_path/Step_15.md
    - Step 16 - Intro to Data Vis: data_path/Step_16.md
    - Step 17 - Interactive Data Vis: data_path/Step_17.md
    - Step 18 - Online Experimentation: data_path/Step_18.md
    - Step 19 - The Pandas Library: data_path/Step_19.md
    - Step 20 - Short Dive into jsPsych: data_path/Step_20.md
    - Step 21 - Processing Data: data_path/Step_21.md
    - Step 22 - Basic Stats: data_path/Step_22.md
    - Step 23 - Data Dive I: data_path/Step_23.md
    - Step 24 - Data Dive II: data_path/Step_24.md
    - Step 25 - What Next?: data_path/Step_25.md
  - Game Dev Path:
    - Game Dev Path: game_dev_path/index.md
    - GD1 - Welcome to the Game Loop: game_dev_path/gd1.md
  - Side Quests:
    - Side Quests: side_quests/index.md
    - F-Strings: side_quests/bonus_printing.md
    - Object Oriented Programming: side_quests/oop.md
    - Pseudocode: side_quests/pseudocode.md
    - Design Patterns: side_quests/design_patterns.md
  - Assistance:
    - assistance/index.md
    - assistance/copilot.md
  - Coding Assignments:
    - coding_assignments/index.md
    - coding_assignments/coding_assignment_01.md
    - coding_assignments/coding_assignment_02.md
    - coding_assignments/coding_assignment_03.md
  - Licenses:
    - licenses/index.md


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true